-- AlterTable
ALTER TABLE "users" ADD COLUMN "banned" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN "banned_at" TIMESTAMPTZ;
ALTER TABLE "users" ADD COLUMN "ban_reason" VARCHAR(500);
