// Precompute Nigeria SVG paths for the OG card so the image route never parses
// the 283KB GeoJSON at request time. Re-run if nigeria-states.geo.json changes:
//   node scripts/gen-og-map.mjs
//
// The source outlines carry far more precision than a 520px box can show, so
// points are projected first and then decimated at sub-pixel distance — the
// result is visually identical at card size and ~20x smaller.
import { readFileSync, writeFileSync } from "node:fs";
import { geoMercator } from "d3-geo";

const W = 520, H = 520, PAD = 8;
const MIN_STEP = 1.1;   // px between kept points
const MIN_RING = 6;     // drop slivers smaller than this bounding box (px)

const geo = JSON.parse(readFileSync(new URL("../src/data/nigeria-states.geo.json", import.meta.url)));
const project = geoMercator().fitExtent([[PAD, PAD], [W - PAD, H - PAD]], geo);

const ringToPath = (ring) => {
  const pts = [];
  let last = null;
  for (const c of ring) {
    const p = project(c);
    if (!p || !Number.isFinite(p[0]) || !Number.isFinite(p[1])) continue;
    if (last && Math.hypot(p[0] - last[0], p[1] - last[1]) < MIN_STEP) continue;
    pts.push(p); last = p;
  }
  if (pts.length < 3) return null;
  const xs = pts.map((p) => p[0]), ys = pts.map((p) => p[1]);
  if (Math.max(...xs) - Math.min(...xs) < MIN_RING && Math.max(...ys) - Math.min(...ys) < MIN_RING) return null;
  const r = (n) => Math.round(n * 10) / 10;
  return "M" + pts.map((p) => `${r(p[0])} ${r(p[1])}`).join("L") + "Z";
};

const featurePath = (f) => {
  const g = f.geometry; if (!g) return null;
  const polys = g.type === "Polygon" ? [g.coordinates] : g.type === "MultiPolygon" ? g.coordinates : [];
  return polys.flatMap((poly) => poly.map(ringToPath).filter(Boolean)).join("") || null;
};

const states = geo.features
  .map((f) => ({ code: f.properties.stateCode, d: featurePath(f) }))
  .filter((s) => s.d);

const out = `// GENERATED by scripts/gen-og-map.mjs — do not edit by hand.
// 37 state outlines projected to a ${W}x${H} box and simplified for the Open Graph card.
export const OG_MAP_SIZE = { width: ${W}, height: ${H} };
export const OG_MAP_STATES: { code: string; d: string }[] = ${JSON.stringify(states)};
`;
writeFileSync(new URL("../src/lib/og-map.generated.ts", import.meta.url), out);
console.log(`wrote ${states.length} states, ${(out.length / 1024).toFixed(1)}KB`);
