export interface ReadmeCounts {
  officials: number;
  cases: number;
  parties: number;
  states: number;
  lgas: number;
}

const F = "```";

/**
 * Generated repo landing page (README.md). Emitted into the bundle on every
 * publish so it is always present and always reflects current counts — a
 * hand-pushed README would be wiped by the force-replace on the next publish.
 */
export function renderReadme(counts: ReadmeCounts, dateIso: string, webBase: string): string {
  const date = dateIso.slice(0, 10);
  const lines = [
    "# OurNigeria — Open Knowledge Bundle",
    "",
    "> ⚠️ **Auto-generated — do not edit by hand.** This repository is rebuilt and force-pushed on every publish; any manual change here is overwritten. To change it, edit the generator in [LogicalOgbonna/ournigeria](https://github.com/LogicalOgbonna/ournigeria) under `apps/api/src/okf/`.",
    "",
    "This is OurNigeria's public civic knowledge, published as an **[Open Knowledge Format (OKF)](https://github.com/GoogleCloudPlatform/knowledge-catalog/tree/main/okf)** bundle: portable Markdown files with YAML frontmatter, cross-linked into a knowledge graph, every fact carrying its source.",
    "",
    `It is built directly from the live OurNigeria database, so it mirrors what's published on ${webBase}.`,
    "",
    `**Last updated:** ${date}`,
    "",
    "## What's inside",
    "",
    "| Type | Count | What it is |",
    "|------|------:|------------|",
    `| [\`officials/\`](officials/) | ${counts.officials.toLocaleString("en-US")} | Public officials — biography, political career, elections, education, assets, awards, family, and legal record |`,
    `| [\`cases/\`](cases/) | ${counts.cases.toLocaleString("en-US")} | Corruption cases — parties involved, timeline of events, amounts |`,
    `| [\`parties/\`](parties/) | ${counts.parties.toLocaleString("en-US")} | Political parties |`,
    `| [\`states/\`](states/) | ${counts.states.toLocaleString("en-US")} | States and the FCT — the geographic hub everything links to |`,
    `| [\`lgas/\`](lgas/) | ${counts.lgas.toLocaleString("en-US")} | Local Government Areas (only those with at least one linked record) |`,
    "",
    "Start at [`index.md`](index.md).",
    "",
    "## Explore the graph",
    "",
    "Open **[`viz.html`](viz.html)** — a self-contained interactive graph (no build step, no server). Force-directed nodes colored by type, full-text search, filter by type, a detail panel that renders each document, and \"Cited by\" backlinks. Download it and open in any browser.",
    "",
    "## The format",
    "",
    "Every concept is one Markdown file with a small YAML frontmatter header:",
    "",
    F + "yaml",
    "---",
    "type: officials",
    "title: Babajide Sanwo-Olu",
    "description: Governor of Lagos State (APC)",
    `resource: ${webBase}/officials/babajide-sanwo-olu`,
    "tags: [lagos, apc, governor]",
    "timestamp: 2026-06-29T00:00:00Z",
    "---",
    F,
    "",
    "- **`type`, `title`, `description`, `resource`, `tags`, `timestamp`** are the queryable fields. `resource` is the canonical page on the live site.",
    "- The body holds the prose and structured sections.",
    "- Concepts cross-link with ordinary Markdown links, e.g. `[Lagos](/states/lagos.md)`, forming a graph rather than a flat list. States and parties accumulate inbound links, so their pages act as live indexes.",
    "",
    "## Provenance",
    "",
    "Every sourced fact renders a footnote: the publisher, a short quote, the source tier, the date retrieved, and — where a takedown-proof copy was captured — an **archived snapshot** link. If an original source goes offline, the document says so and the archived copy becomes the reference. The point is civic claims you can trace back to where they came from.",
    "",
    "## Using it",
    "",
    "- **Download the whole thing:** [`bundle.tar.gz`](bundle.tar.gz)",
    "- **Clone:** `git clone https://github.com/LogicalOgbonna/ournigeria-knowledge`",
    "- **Feed it to an AI:** it's plain Markdown — point any RAG pipeline, agent, or search index at the files. The frontmatter gives structured filters; the bodies give context.",
    "- **Read on GitHub:** every file renders here and the cross-links work.",
    "",
    "## How it's built and refreshed",
    "",
    "Generated by the OKF exporter in [LogicalOgbonna/ournigeria](https://github.com/LogicalOgbonna/ournigeria) (`apps/api/src/okf/`): it reads the production database, renders each concept, and force-pushes the result here. Rebuilt on a nightly schedule. The output is deterministic — a publish with no data changes produces no commit.",
    "",
    "## Links",
    "",
    `- Main site: ${webBase}`,
    "- Source & generator: https://github.com/LogicalOgbonna/ournigeria",
    "- OKF specification: https://github.com/GoogleCloudPlatform/knowledge-catalog/tree/main/okf",
    "",
    "---",
    "",
    "OurNigeria — open civic data for Nigeria. Use it, fork it, build on it.",
    "",
  ];
  return lines.join("\n");
}
