"""Write reconciliation results into the seed (additions) + emit corrections.

Additions are durable via the deploy-run ``sync-admin-hierarchy.mjs`` (upsert
only). Same-tier conflicts (a ward already mapped to a different constituency)
require a human-approved correction migration — additions never generate one.

Everything here is pure/functional over in-memory lists; the CLI owns the actual
file reads/writes and the ``--apply`` gate.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from .paths import SEED_DIR

CONSTITUENCY_WARDS_SEED = SEED_DIR / "constituency-wards.json"
SENATORIAL_LGAS_SEED = SEED_DIR / "senatorial-district-lgas.json"


def _today_month() -> str:
    return date.today().strftime("%Y-%m")


def apply_additions(
    existing_rows: list[dict],
    new_maps: list[tuple[str, str, str]],
    source: str,
    source_url: str,
    source_date: str | None = None,
) -> list[dict]:
    """Merge ``(constituency_code, ward_code, confidence)`` additions into the
    constituency-wards seed shape.

    Keyed by ``(constituency_code, ward_code)``: existing pairs are left fully
    untouched (no source/confidence overwrite); unrelated rows pass through
    unchanged; only genuinely new pairs are appended.
    """
    source_date = source_date or _today_month()
    seen: set[tuple[str, str]] = {
        (r["constituency_code"], r["ward_code"]) for r in existing_rows
    }
    merged = list(existing_rows)
    for constituency_code, ward_code, confidence in new_maps:
        key = (constituency_code, ward_code)
        if key in seen:
            continue
        seen.add(key)
        merged.append(
            {
                "constituency_code": constituency_code,
                "ward_code": ward_code,
                "source": source,
                "source_url": source_url,
                "source_date": source_date,
                "confidence": confidence,
            }
        )
    return merged


def apply_senatorial_additions(
    existing_rows: list[dict],
    new_maps: list[tuple[str, str, str]],
    source: str,
    source_url: str,
    source_date: str | None = None,
) -> list[dict]:
    """Merge ``(senatorial_district_code, lga_code, confidence)`` additions into
    the senatorial-district-lgas seed shape (same dedupe semantics)."""
    source_date = source_date or _today_month()
    seen: set[tuple[str, str]] = {
        (r["senatorial_district_code"], r["lga_code"]) for r in existing_rows
    }
    merged = list(existing_rows)
    for sd_code, lga_code, confidence in new_maps:
        key = (sd_code, lga_code)
        if key in seen:
            continue
        seen.add(key)
        merged.append(
            {
                "senatorial_district_code": sd_code,
                "lga_code": lga_code,
                "source": source,
                "source_url": source_url,
                "source_date": source_date,
                "confidence": confidence,
            }
        )
    return merged


def emit_corrections_migration(conflicts: list[dict]) -> str | None:
    """Build a migration SQL string that removes the stale same-tier mapping for
    each human-approved conflict. The seed then carries the corrected mapping,
    which the deploy-run sync upserts.

    Returns None when there are no conflicts (additions need no migration).
    """
    if not conflicts:
        return None
    lines = [
        "-- Ward-reconciliation corrections: remove stale same-tier ward mappings",
        "-- so the corrected seed mapping (loaded by sync-admin-hierarchy.mjs) wins.",
        "-- Generated by reconcile_wards.apply.emit_corrections_migration.",
        "",
    ]
    for c in conflicts:
        ward = c["ward_code"].replace("'", "''")
        existing = c["existing_constituency"].replace("'", "''")
        proposed = c.get("proposed_constituency", "")
        lines.append(
            f"-- ward {ward}: {existing} -> {proposed} (tier {c.get('tier', '?')})"
        )
        lines.append(
            "DELETE FROM constituency_wards "
            f"WHERE ward_code = '{ward}' "
            f"AND constituency_code = '{existing}';"
        )
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# File IO helpers (used by the CLI's --apply path)
# ---------------------------------------------------------------------------


def load_seed(path: Path) -> list[dict]:
    return json.loads(path.read_text())


def write_seed(path: Path, rows: list[dict]) -> None:
    path.write_text(json.dumps(rows, indent=2) + "\n")
